import Head from "next/head";
import Image from "next/image";
import NotHome from "../components/Home/Home";
import Services from "../components/Services/Services";
import Projects from "../components/Projects/Projects";
import Contact from "../components/Contact/Contact";
// import { Inter } from "next/font/google";

export default function Home() {
  return (
    <div className="bg-slate-100">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex gap-20 flex-col">
        <NotHome />
        <Services />
        <Projects />
        <Contact />
      </div>
    </div>
  );
}
